### ISSUE TITLE
Unable to upload APK if Turkish language is not configured

### ISSUE THREAD

**Issue by ssb22** [Natgho/HMS-Publishing-API#1]
When I try to use `upload_app` for an application which does not have a Turkish version, I get a return value with code 200 but with `content` set to:

    b'{"ret":{"code":204144650,"msg":"[AppGalleryConnectPublishService]The language does not exist !"}}'

and the upload does not succeed.

This can be worked around by removing (or commenting out) the

    'lang': 'tr-TR',

on line 126 of `publishing_api.py`.  Huawei's developer documentation says language is mandatory for images and videos, but not for APKs, so I suggest leaving it out because not everyone has Turkish configured.  Thanks.

**Comment by Natgho** [comment]
Hi,

When I testing application, I put sample language for testing and forgot the remove. Your PR accepted, thank you for contribution 💯
